function [ dial_3 ] = TimeEditInstruction(  )
%SecondInstruction Summary of this function goes here
%   Detailed explanation goes here

StartPosition = [300,300];
positionBox = [StartPosition , 400 ,300];
positionTxt = [30 70 350 200];
positionBtn = [150 15 100 35];
txt_content = [ 'Most of the disturbs occur during a specific time interval. ',...
                '(initialize to: t1=90 , t2=110)',...
                sprintf('\n\n'),...
                'You can set the interval using the keyboard.  ',...
                '**Notice that Transient`s duration is much shorter '];

dial_3 = dialog('Position',positionBox,'Name','Using the GUI: time interval edition');
dial_3.Color =  [0 ,0.1 ,0.2];
txt = uicontrol('Parent',dial_3,...
    'Style','text',...
    'Position',positionTxt,...
    'String',txt_content);
txt.FontSize = 14;

btn = uicontrol('Parent',dial_3,...
    'Position',positionBtn,...
    'String','Got it',...
    'Callback','delete(gcf)');

end

